name: bitcoin-scanner
services:
- name: bitcoin-scanner
  source_dir: /
  github:
    repo: JackChen6203/bitcoin_calculator
    branch: master
  run_command: ./bitcoin_scanner
  environment_slug: go
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: DISCORD_WEBHOOK_URL
    scope: RUN_TIME
    type: SECRET

databases:
- name: bitcoin-db
  engine: PG
  num_nodes: 1
  size: db-s-dev-database
  version: "14"